name: d1
channels: [conda-forge, pytorch, nvidia]
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.3.1 --index-url https://download.pytorch.org/whl/cu121
      - transformers==4.55.4
      - datasets==4.0.0
      - accelerate==1.10.1
      - huggingface_hub==0.34.4
      - sentencepiece
      - safetensors
      - bitsandbytes==0.43.3
      - trl==0.9.6

