model_name_or_path: GSAI-ML/LLaDA-8B-Instruct
per_device_batch_size: 1
grad_accum_steps: 8
kl_coef: 0.02
entropy_penalty_coef: 0.1
entropy_penalty_schedule: linear
entropy_warmup_steps: 500
total_updates: 1000
gen_max_new_tokens: 512
ref_model: outputs/sft_ckpt
